[theme]
base = "dark"
primaryColor = "#615fff"
backgroundColor = "#1d293d"
secondaryBackgroundColor = "#0f172b"
textColor = "#e2e8f0"
showWidgetBorder = true
borderColor = "#314158"
dataframeHeaderBackgroundColor = "#1d293d"
font = "sans serif"
