# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import asyncio
import os
import sys
from datetime import datetime, timezone

# Add current directory to python path to allow importing app module
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

# Ensure MCP servers and OAuth auth flows are bypassed since we are running 
# in batch mode for news sentiment analysis.
os.environ["INTEGRATION_TEST"] = "TRUE"

from app.tools.data_ingestion import ingest_market_news
from app.tools.ranking import process_sentiment_rankings
from app.tools.bigquery_service import setup_bigquery, insert_sentiment
from app.agent import sentiment_agent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.genai import types

def print_portfolio_table(portfolio: list) -> None:
    """Renders a beautiful ASCII table of the ranked portfolio and trade signals."""
    print("\n" + "="*95)
    print(f"{'Ticker':<8} | {'Raw Score':<9} | {'Rank (1-10)':<12} | {'Signal':<11} | {'Thesis'}")
    print("="*95)
    for item in portfolio:
        thesis = item.get("thesis", "")
        # Truncate thesis if it's too long for a clean terminal output
        truncated_thesis = thesis[:50] + "..." if len(thesis) > 50 else thesis
        print(f"{item['ticker']:<8} | {item['raw_score']:<9.2f} | {item['relative_rank']:<12} | {item['signal']:<11} | {truncated_thesis}")
    print("="*95 + "\n")

async def run_pipeline(dataset_id: str = "portfolio_analytics") -> None:
    print(f"[{datetime.now(timezone.utc).isoformat()}] Starting AI Infrastructure Analyst pipeline...")

    # Step 1: Initialize BigQuery Dataset and Tables
    print(f"\n1. Setting up BigQuery dataset '{dataset_id}' and tables...")
    setup_bigquery(dataset_id=dataset_id)
    print("   Dataset and tables verified/created successfully.")

    # Step 2: Ingest Latest Market News
    print("\n2. Ingesting latest 24h market news from yfinance...")
    news_dict = ingest_market_news()
    print(f"   Successfully fetched news feed for {len(news_dict)} tickers.")

    # Step 3: Run structured sentiment agent (Part 1 - LLM call)
    print("\n3. Triggering Gemini 1.5 Flash sentiment analysis...")
    session_service = InMemorySessionService()
    session = await session_service.create_session(user_id="cron_job", app_name="sentiment")
    runner = Runner(agent=sentiment_agent, session_service=session_service, app_name="sentiment")

    message = types.Content(
        role="user",
        parts=[types.Part.from_text(text=f"Analyze these news articles:\n{news_dict}")]
    )

    # Execute agent run
    async for _ in runner.run_async(
        new_message=message,
        user_id="cron_job",
        session_id=session.id,
    ):
        pass

    # Retrieve updated session containing Pydantic output schema
    session = await session_service.get_session(user_id="cron_job", session_id=session.id, app_name="sentiment")
    sentiment_result = session.state.get("sentiment_result")
    if not sentiment_result:
        raise RuntimeError("Failed to retrieve sentiment analysis output from the LLM agent.")
    
    print("   Structured sentiment scores generated by Gemini.")

    # Step 4: Run deterministic Python ranking logic (Part 2)
    print("\n4. Running deterministic ranking and signal assignment...")
    ranked_portfolio = process_sentiment_rankings(sentiment_result)

    # Attach the raw news stories to each portfolio item for BigQuery auditing
    for item in ranked_portfolio:
        ticker = item["ticker"]
        item["raw_news"] = news_dict.get(ticker, [])

    # Step 5: Log decisions into Google Cloud BigQuery
    print(f"\n5. Logging analysis results to BigQuery dataset '{dataset_id}'...")
    insert_sentiment(ranked_portfolio, dataset_id=dataset_id)
    print("   Decisions written to 'infrastructure_sentiment' table.")

    # Step 6: Print results summary
    print("\n=== Pipeline Execution Completed successfully ===")
    print_portfolio_table(ranked_portfolio)

if __name__ == "__main__":
    asyncio.run(run_pipeline())
